---
- name: Tests
  hosts: ansibletarget
  become: yes
  tasks:
#    - ping:


    - name: Install python-setuptools
      apt:
         name: python3-setuptools
         state: present

    - name: Install python3-pip
      apt:
         name: python3-pip
         state: present

    - name: Install wheel
      pip:
         name:
           - wheel
         state: present

    - name: Install gunicorn
      pip:
         name:
           - gunicorn
         state: present

    - name: Install flask
      pip:
         name: flask
         executable: pip3
         state: present

    - name: Uninstall Apache2
      apt:
         name: apache2
         state: absent

    - name: Install Nginx
      apt:
         name: nginx
         state: present

    - name: start nginx
      service: 
        name: nginx
        state: started
        enabled: yes

    - name: copy myproject.py
      copy:
        src: ~/myproject
        dest: /etc
        owner: osboxes
        group: osboxes
        mode: '0755'
#    become: yes
#    tags: copy_skel

    - name: start myproject.py
      command: python3 /etc/myproject/myproject.py
      async: 5
      poll: 10


